
language: python

python:
  - "3.6"

sudo: false
cache: pip3

install:
 - pip3 install -r api/requirements.txt
 - pip3 install coverage

 # change from 'script: python setup.py test' to this
script:
 - coverage run api/test_views.py
 - pytest

env:
  global:
    - CC_TEST_REPORTER_ID=89ad622277ecfee77d06deb6f2ab8b0377e7c2545fb99275064179abbf59afb2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
