
language: python

python:
  - "3.6"

sudo: false
cache: pip3

install:
 - pip3 install -r api/requirements.txt

# change from 'script: python setup.py test' to this
script:
 - coverage3 run --source test_views.py
 - pytest


